services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=mongodbTest
      - MONGO_INITDB_ROOT_USERNAME=admin # Thiết lập user root
      - MONGO_INITDB_ROOT_PASSWORD=admin123
    volumes:
      # thư mục lưu data và file config
      - ./mongodb:/data/db